### ISSUE TITLE
[DOCS] - No warning about not finding MetaWardsData

### ISSUE THREAD

**Issue by lohedges** [metawards/MetaWards#63]
The [Getting Started](https://metawards.org/tutorial/part01/01_getting_started.html) section of the tutorial suggests that I should see a warning telling me that MetaWardsData couldn't be found if I've not set things up as described [here](https://metawards.org/model_data.html). However, I only see the following output:

```
$ metawards --version

     *************************************
     metawards version 0.11.1+11.g28b30254
     *************************************

            -- Source information --
repository: git@github.com:metawards/MetaWards.git
                 branch: devel
revision: 28b30254053ae2f5bdc8d4cc8d77c6c945ce137b
    last modified: 2020-05-11T18:07:58+0100

          -- Additional information --
Visit https://metawards.org for more information
  about metawards, its authors and its license
```

MetaWardsData isn't visible to MetaWards, so any attempted simulation fails, e.g.:

```
$ metawards --disease lurgy

     *************************************
     metawards version 0.11.1+11.g28b30254
     *************************************

            -- Source information --
repository: git@github.com:metawards/MetaWards.git
                 branch: devel
revision: 28b30254053ae2f5bdc8d4cc8d77c6c945ce137b
    last modified: 2020-05-11T18:07:58+0100

          -- Additional information --
Visit https://metawards.org for more information
  about metawards, its authors and its license

Command used to run this job:
/home/lester/.conda/envs/metawards/bin/metawards --disease lurgy

Performing a single run of each set of parameters

Number of threads to use for each model run is 8

Using random number seed 73984519

Day zero is Tuesday May 12 2020
Traceback (most recent call last):
  File "/home/lester/.conda/envs/metawards/bin/metawards", line 11, in <module>
    load_entry_point('metawards==0.11.1+11.g28b30254', 'console_scripts', 'metawards')()
  File "/home/lester/.conda/envs/metawards/lib/python3.8/site-packages/metawards-0.11.1+11.g28b30254-py3.8-linux-x86_64.egg/metawards/app/run.py", line 793, in cli
    (repository, repository_version) = Parameters.get_repository(
  File "/home/lester/.conda/envs/metawards/lib/python3.8/site-packages/metawards-0.11.1+11.g28b30254-py3.8-linux-x86_64.egg/metawards/_parameters.py", line 211, in get_repository
    raise FileNotFoundError(
FileNotFoundError: Cannot find the MetaWardsData repository at /home/lester/GitHub/MetaWardsData
```

Exporting the path to MetaWardsData allows the simulation to run, but the output of `metawards --version` stays the same.

**Comment by chryswoods** [comment]
This is a difficult one, as technically it is possible to run a simulation without MetaWardsData - you just move all of the model files into your own directory and specify them with their full paths.

I think the right action would be for the "--version" to look for MetaWardsData, and to print out its version there (as this is useful). Then if it can't be found, it prints a warning but not an error.

I'll make the change later today.
