### ISSUE TITLE
jpg format not supported by matplotlib

### ISSUE THREAD

**Issue by lohedges** [metawards/MetaWards#65]
When running the plotting command from the [tutorial](https://metawards.org/tutorial/part01/03_plotting.html) I get the following error:

```
metawards-plot --input output/results.csv.bz2
Importing graphics modules...
Reading data from output/results.csv.bz2...
Creating overview plot(s)...
Saving figure output/overview.jpg
Traceback (most recent call last):
  File "/home/lester/.conda/envs/metawards/bin/metawards-plot", line 11, in <module>
    load_entry_point('metawards==0.11.1+11.g28b30254', 'console_scripts', 'metawards-plot')()
  File "/home/lester/.conda/envs/metawards/lib/python3.8/site-packages/metawards-0.11.1+11.g28b30254-py3.8-linux-x86_64.egg/metawards/app/plot.py", line 87, in cli
    filenames = save_summary_plots(results=filename,
  File "/home/lester/.conda/envs/metawards/lib/python3.8/site-packages/metawards-0.11.1+11.g28b30254-py3.8-linux-x86_64.egg/metawards/analysis/_summary_plot.py", line 477, in save_summary_plots
    figs = create_overview_plot(df, output_dir=output_dir,
  File "/home/lester/.conda/envs/metawards/lib/python3.8/site-packages/metawards-0.11.1+11.g28b30254-py3.8-linux-x86_64.egg/metawards/analysis/_summary_plot.py", line 177, in create_overview_plot
    fig.savefig(filename, dpi=dpi)
  File "/home/lester/.conda/envs/metawards/lib/python3.8/site-packages/matplotlib/figure.py", line 2203, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/lester/.conda/envs/metawards/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2043, in print_figure
    canvas = self._get_output_canvas(format)
  File "/home/lester/.conda/envs/metawards/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 1981, in _get_output_canvas
    raise ValueError(
ValueError: Format 'jpg' is not supported (supported formats: eps, pdf, pgf, png, ps, raw, rgba, svg, svgz)
```
For some reason, it looks like the version of MatplotLib that I have installed doesn't support the `jpg` format. Perhaps we can't assume that all graphics formats are supported by all MatplotLib installations.

**Comment by lohedges** [comment]
For reference, this occurs for both pip and conda installs of pandas and matplotlib within a clean python 3.8 conda environment on Linux.

**Comment by lohedges** [comment]
However, the plots in the [example notebook](https://metawards.org/_downloads/0a4b2ec193ed97e2aad7418818ebb69f/1_3_plotting.ipynb) work fine.

**Comment by chryswoods** [comment]
conda fails to install pillow (or PIL) which means that jpg support is missing. Fix this using;

```
pip install pillow
```

Code should be updated to check if PIL is available, and if not, switch the default from jpg to png

**Comment by lohedges** [comment]
Yes, installing `pillow` fixed the problem. However, I now have `*.jpg` files in the output directory, rather than the `*.pdf` files described in the tutorial, which might confuse someone.
